const emotions: { name: string; image: string }[] = [
    {"name": "Sad", "image": "/sobbing-face.png"},
    {"name": "Silly", "image": "/zany-face.png"},
    {"name": "Crazy", "image": "/upside-down-dizzy-face.png"},
    {"name": "Tired", "image": "/yawning-sleeping-face.png"},
    {"name": "Sick", "image": "/face-with-thermometer.png"},
    {"name": "Angry", "image": "/angry-face.png"},
    {"name": "Alone", "image": "/pleading-face.png"},
    {"name": "Demotivated", "image": "/woozy-neutral-face.png"},
    {"name": "Drained", "image": "/weary-face.png"},
    {"name": "Exhausted", "image": "/tongue-on-the-floor-face.png"},
    {"name": "Emotional", "image": "/loudly-crying-face.png"},
    {"name": "Annoyed", "image": "/skeptical-face.png"},
    {"name": "Bored", "image": "/huge-yawn-face.png"},
    {"name": "Disappointed", "image": "😞"},
    {"name": "Sorry", "image": "🙏"},
    {"name": "Worried", "image": "😟"},
    {"name": "Bad", "image": "😕"},
    {"name": "Down", "image": "😔"},
    {"name": "Goofy", "image": "😜"},
    {"name": "Confused", "image": "😕"},
    {"name": "Low", "image": "😞"},
    {"name": "Broken", "image": "💔"},
    {"name": "Depressed", "image": "😢"},
    {"name": "Concerned", "image": "😟"},
    {"name": "Lonely", "image": "😔"},
    {"name": "Irritated", "image": "😠"},
    {"name": "Incomplete", "image": "🤕"},
    {"name": "Annoyed", "image": "😤"},
    {"name": "Puzzled", "image": "🤔"},
    {"name": "Surprised", "image": "😲"},
    {"name": "Furious", "image": "😡"},
    {"name": "Fed up", "image": "😣"},
    {"name": "Stressed", "image": "😰"},
    {"name": "Meh", "image": "😑"},
    {"name": "Terrible", "image": "😖"},
    {"name": "Frustrated", "image": "😤"},
    {"name": "Old", "image": "👴"},
    {"name": "Ashamed", "image": "😳"},
    {"name": "Stupid", "image": "🤦"},
    {"name": "Like dog crap", "image": "💩"},
    {"name": "Lazy", "image": "😴"},
    {"name": "Lost", "image": "😕"},
    {"name": "Hurt", "image": "😢"},
    {"name": "Insecure", "image": "😟"},
    {"name": "Dumb", "image": "🤦"},
    {"name": "Weak", "image": "😩"},
    {"name": "Awful", "image": "😖"},
    {"name": "Rough", "image": "😣"},
    {"name": "Like dying", "image": "💀"},
    {"name": "Weird", "image": "😳"},
    {"name": "Crappy", "image": "💩"},
    {"name": "Worthless", "image": "😞"},
    {"name": "Helpless", "image": "😔"},
    {"name": "Hopeless", "image": "😞"},
    {"name": "Miserable", "image": "😩"},
    {"name": "Mad", "image": "😡"},
    {"name": "Overwhelmed", "image": "😫"},
    {"name": "Awkward", "image": "😬"},
    {"name": "Dirty", "image": "😷"},
    {"name": "Jealous", "image": "😒"},
    {"name": "Sore", "image": "😖"},
    {"name": "Scared", "image": "😨"},
    {"name": "Unimportant", "image": "😔"},
    {"name": "Naked", "image": "😳"},
    {"name": "Small", "image": "😞"},
    {"name": "Useless", "image": "😖"},
    {"name": "Upset", "image": "😣"},
    {"name": "Offen
];
